GET http://localhost:5181/todos?

###
GET http://localhost:5181/todos?page=2&pagesize=4&sortBy=status&asc=true

###
GET http://localhost:5181/todos/searchbyname?page=1&pagesize=1&searchname=c

###
PUT http://localhost:5181/todos/1
Content-Type: application/json

{
    "name": "Prepare Meal",
    "status": "Pending",
    "priority": "Medium",
    "duedate": "2025-04-01"
}

###
POST http://localhost:5181/todos
Content-Type: application/json

{
    "name": "Workout",
    "status": "Pending",
    "priority": "Medium",
    "duedate": "2025-04-01"
}

###
DELETE http://localhost:5181/todos/12