GET http://localhost:5181/todos

###
GET http://localhost:5181/todos/duedate/true

###
GET http://localhost:5181/todos/Code

###
PUT http://localhost:5181/todos/23
Content-Type: application/json

{
    "name": "Wash dishes",
    "iscompleted": false,
    "priority": "Medium",
    "duedate": "2025-03-30"
}

###
POST http://localhost:5181/todos
Content-Type: application/json

{
    "name": "Shower",
    "iscompleted": false,
    "priority": "High",
    "duedate": "2025-03-30"
}

###
DELETE http://localhost:5181/todos/24